import { OutreachEntry, CollegeEntry, CalendarEvent, NotificationItem } from "./types";

// ─── Outreach Data ───
export const outreachData: OutreachEntry[] = [
  { sno: 1, name: "Rohan Abeyaratne", email: "rohan@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 2, name: "Faez Ahmed", email: "faez@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 3, name: "Akerson", email: "akerson@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 4, name: "Tonio Buonassisi", email: "buonassi@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 5, name: "Jacopo Buongiorno", email: "buongiorn@mit.edu", university: "MIT", researchFocus: "Nuclear Science and Engineering", dateSent: "2026-06-20", status: "sent" },
  { sno: 6, name: "Gossard", email: "GOSSARD@MIT.EDU", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 7, name: "Timothy G. Gutowski", email: "GUTOWSKI@MIT.EDU", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 8, name: "Nicolas Hadjiconstantinou", email: "NGH@MIT.EDU", university: "MIT", researchFocus: "materials", dateSent: "2026-06-20", status: "sent" },
  { sno: 9, name: "David E. Hardt", email: "hardt@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 10, name: "A. John Hart", email: "ajhart@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 11, name: "Douglas Hart", email: "dphart@mit.edu", university: "MIT", researchFocus: "Controls; Instrumentation and Robotics", dateSent: "2026-06-20", status: "sent" },
  { sno: 12, name: "Neville Hogan", email: "neville@mit.edu", university: "MIT", researchFocus: "Controls; Instrumentation and Robotics", dateSent: "2026-06-20", status: "responded", responseDate: "2026-06-20", responseSummary: "No new appointments in the coming year" },
  { sno: 13, name: "Anette Hosoi", email: "PEKO@MIT.EDU", university: "MIT", researchFocus: "materials", dateSent: "2026-06-20", status: "sent" },
  { sno: 14, name: "Ian Hunter", email: "IHUNTER@MIT.EDU", university: "MIT", researchFocus: "controls", dateSent: "2026-06-20", status: "sent" },
  { sno: 15, name: "Sang-Gook Kim", email: "SANGKIM@MIT.EDU", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 16, name: "Sangbae Kim", email: "SANGBAE@MIT.EDU", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 17, name: "Steven B. Leeb", email: "SBLEEB@MIT.EDU", university: "MIT", researchFocus: "controls", dateSent: "2026-06-20", status: "sent" },
  { sno: 18, name: "John J. Leonard", email: "JLEONARD@MIT.EDU", university: "MIT", researchFocus: "controls", dateSent: "2026-06-20", status: "sent" },
  { sno: 19, name: "Nicholas Makris", email: "MAKRIS@MIT.EDU", university: "MIT", researchFocus: "materials", dateSent: "2026-06-20", status: "sent" },
  { sno: 20, name: "Wojciech Matusik", email: "wojciech@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 21, name: "Gareth H. McKinley", email: "GARETH@MIT.EDU", university: "MIT", researchFocus: "materials", dateSent: "2026-06-20", status: "sent" },
  { sno: 22, name: "Stefanie Mueller", email: "mueller_@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 23, name: "David Moore Parks", email: "DMPARKS@MIT.EDU", university: "MIT", researchFocus: "materials", dateSent: "2026-06-20", status: "sent" },
  { sno: 24, name: "Anthony T. Patera", email: "patera@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 25, name: "Nicholas M. Patrikalakis", email: "NMP@MIT.EDU", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 26, name: "Thomas Peacock", email: "tomp@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 27, name: "Carlos Portela", email: "cportela@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 28, name: "Ritu Raman", email: "ritur@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 29, name: "Ellen Roche", email: "etr@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 30, name: "Sanjay E. Sarma", email: "sesarma@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 31, name: "Warren Paul Seering", email: "Seering@MIT.edu", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 32, name: "Alexander H. Slocum", email: "slocum@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "responded", responseDate: "2026-06-21", responseSummary: "Retiring soon - no new students. Suggested industry-funded research." },
  { sno: 33, name: "Jean-Jacques E. Slotine", email: "JJS@MIT.EDU", university: "MIT", researchFocus: "controls", dateSent: "2026-06-20", status: "sent" },
  { sno: 34, name: "Russ Tedrake", email: "russt@mit.edu", university: "MIT", researchFocus: "Controls; Instrumentation and Robotics", dateSent: "2026-06-20", status: "sent" },
  { sno: 35, name: "David L. Trumper", email: "trumper@mit.edu", university: "MIT", researchFocus: "Controls; Instrumentation and Robotics", dateSent: "2026-06-20", status: "sent" },
  { sno: 36, name: "Kripa Varanasi", email: "kripa@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 37, name: "David Wallace", email: "DRWALLAC@MIT.EDU", university: "MIT", researchFocus: "manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 38, name: "Sherrie Wang", email: "sherwang@mit.edu", university: "MIT", researchFocus: "Controls; Instrumentation and Robotics", dateSent: "2026-06-20", status: "sent" },
  { sno: 39, name: "Tomasz Wierzbicki", email: "WIERZ@MIT.EDU", university: "MIT", researchFocus: "materials", dateSent: "2026-06-20", status: "sent" },
  { sno: 40, name: "James H. Williams Jr.", email: "jhwill@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 41, name: "Amos G. Winter", email: "awinter@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 42, name: "Maria Yang", email: "mcyang@mit.edu", university: "MIT", researchFocus: "Design and Manufacturing", dateSent: "2026-06-20", status: "sent" },
  { sno: 43, name: "Kamal Youcef-Toumi", email: "YOUCEF@MIT.EDU", university: "MIT", researchFocus: "controls", dateSent: "2026-06-20", status: "sent" },
  { sno: 44, name: "Xuanhe Zhao", email: "zhaox@mit.edu", university: "MIT", researchFocus: "Mechanics", dateSent: "2026-06-20", status: "sent" },
  { sno: 45, name: "Raphael Zufferey", email: "raphz@mit.edu", university: "MIT", researchFocus: "Controls; Instrumentation and Robotics", dateSent: "2026-06-20", status: "responded", responseDate: "2026-06-21", responseSummary: "Traveling until June 26 - follow up after return" },
  { sno: 46, name: "Farzaneh Barati", email: "barati@cmu.edu", university: "Carnegie Mellon", researchFocus: "Advanced manufacturing; transport phenomena; micro/nanoengin", dateSent: "2026-06-20", status: "sent" },
  { sno: 47, name: "Sarah Bergbreiter", email: "sbergbre@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Bioinspired robotics; biomanufacturing; soft robotics", dateSent: "2026-06-20", status: "sent" },
  { sno: 48, name: "Jack Beuth", email: "beuth@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Additive manufacturing; machine learning; advanced manufactu", dateSent: "2026-06-20", status: "sent" },
  { sno: 49, name: "Ophelia Bolmin", email: "obolmin@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Vibrations; finite element modeling; biological engineering", dateSent: "2026-06-20", status: "sent" },
  { sno: 50, name: "Jonathan Cagan", email: "cagan@cmu.edu", university: "Carnegie Mellon", researchFocus: "Optimization; computer engineering; product design", dateSent: "2026-06-20", status: "sent" },
  { sno: 51, name: "Maarten de Boer", email: "mpdebo@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Additive manufacturing; materials science; devices and mater", dateSent: "2026-06-20", status: "sent" },
  { sno: 52, name: "Frederike Dümbgen", email: "fduembgen@cmu.edu", university: "Carnegie Mellon", researchFocus: "Dynamics; legged and aerial robotics; robotics", dateSent: "2026-06-20", status: "sent" },
  { sno: 53, name: "Noelia Grande Gutiérrez", email: "ngrandeg@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Biomechanics; fluid mechanics; computer-aided design", dateSent: "2026-06-21", status: "sent" },
  { sno: 54, name: "Eni Halilaj", email: "ehalilaj@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Bioengineering; computational modeling; human health", dateSent: "2026-06-21", status: "sent" },
  { sno: 55, name: "Reeja Jayan", email: "bjayan@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Manufacturing workforce; devices and material manipulation; ", dateSent: "2026-06-21", status: "sent" },
  { sno: 56, name: "Aaron Johnson", email: "amj1@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Legged and aerial robotics; controls and automation; biomech", dateSent: "2026-06-21", status: "sent" },
  { sno: 57, name: "Inseung Kang", email: "inseung@cmu.edu", university: "Carnegie Mellon", researchFocus: "Rehabilitation; control theory; neuroscience", dateSent: "2026-06-21", status: "sent" },
  { sno: 58, name: "Levent Burak Kara", email: "lkara@cmu.edu", university: "Carnegie Mellon", researchFocus: "Digital twins; computational design; manufacturing workforce", dateSent: "2026-06-21", status: "sent" },
  { sno: 59, name: "Philip LeDuc", email: "prl@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Tissue engineering; human health; biomaterials", dateSent: "2026-06-21", status: "sent" },
  { sno: 60, name: "Shawn Litster", email: "litster@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Advanced vehicle systems; computational engineering; energy", dateSent: "2026-06-21", status: "sent" },
  { sno: 61, name: "Carmel Majidi", email: "cmajidi@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Medical device manufacturing; soft robotics; devices and mat", dateSent: "2026-06-21", status: "sent" },
  { sno: 62, name: "Jonathan Malen", email: "jonmalen@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Energy; micro/nanoengineering; materials for energy efficien", dateSent: "2026-06-21", status: "sent" },
  { sno: 63, name: "Christopher McComb", email: "ccm@cmu.edu", university: "Carnegie Mellon", researchFocus: "Advanced manufacturing; human-machine teaming; energy", dateSent: "2026-06-21", status: "sent" },
  { sno: 64, name: "Alan McGaughey", email: "mcgaughey@cmu.edu", university: "Carnegie Mellon", researchFocus: "Materials science; nanoscience; emerging energy technologies", dateSent: "2026-06-21", status: "sent" },
  { sno: 65, name: "Jeremy Michalek", email: "jmichalek@cmu.edu", university: "Carnegie Mellon", researchFocus: "Engineered systems; advanced vehicle systems; mechanical eng", dateSent: "2026-06-21", status: "sent" },
  { sno: 66, name: "Sneha Prabha Narra", email: "snarra@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Digital backbone; manufacturing workforce; additive manufact", dateSent: "2026-06-21", status: "sent" },
  { sno: 67, name: "Francis Ogoke", email: "oogoke@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Digital twins; manufacturing engineering; computational mode", dateSent: "2026-06-21", status: "sent" },
  { sno: 68, name: "Burak Ozdoganlar", email: "ozdoganlar@cmu.edu", university: "Carnegie Mellon", researchFocus: "Additive manufacturing; medical devices; vibrations", dateSent: "2026-06-21", status: "sent" },
  { sno: 69, name: "Rahul Panat", email: "rpanat@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Climate resilience; biomanufacturing; advanced manufacturing", dateSent: "2026-06-21", status: "sent" },
  { sno: 70, name: "Albert Presto", email: "apresto@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Environmental engineering; sustainability; smart cities", dateSent: "2026-06-21", status: "sent" },
  { sno: 71, name: "Yoed Rabin", email: "rabin@cmu.edu", university: "Carnegie Mellon", researchFocus: "Medical devices; heat transfer in biological systems; biomed", dateSent: "2026-06-21", status: "sent" },
  { sno: 72, name: "Sheng Shen", email: "shengshe@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Energy; AI energy and climate; materials for energy efficien", dateSent: "2026-06-21", status: "sent" },
  { sno: 73, name: "Kenji Shimada", email: "shimada@cmu.edu", university: "Carnegie Mellon", researchFocus: "Medical devices; computational engineering; robotics", dateSent: "2026-06-21", status: "sent" },
  { sno: 74, name: "Satbir Singh", email: "satbirs@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Energy; environmental engineering; computational engineering", dateSent: "2026-06-21", status: "sent" },
  { sno: 75, name: "Ryan Sullivan", email: "ryansull@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Grid and energy infrastructure; atmospheric particle studies", dateSent: "2026-06-21", status: "sent" },
  { sno: 76, name: "Rebecca Taylor", email: "bex@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Advanced manufacturing; manufacturing workforce; bioengineer", dateSent: "2026-06-21", status: "sent" },
  { sno: 77, name: "Conrad Tucker", email: "conradt@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Artificial intelligence; optimization; data mining", dateSent: "2026-06-21", status: "sent" },
  { sno: 78, name: "Liwei Wang", email: "liweiw@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "3D printing; advanced manufacturing; optimization", dateSent: "2026-06-21", status: "sent" },
  { sno: 79, name: "Douglas Weber", email: "dougweber@cmu.edu", university: "Carnegie Mellon", researchFocus: "Neuromodulation; neural engineering; bioengineering", dateSent: "2026-06-21", status: "sent" },
  { sno: 80, name: "Victoria Webster-Wood", email: "vwebster@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Bioinspired robotics; bioengineering; sustainability", dateSent: "2026-06-21", status: "sent" },
  { sno: 81, name: "Kate Whitefoot", email: "kwhitefoot@cmu.edu", university: "Carnegie Mellon", researchFocus: "Energy; advanced vehicle systems; additive manufacturing", dateSent: "2026-06-21", status: "sent" },
  { sno: 82, name: "Jessica Zhang", email: "jessicaz@andrew.cmu.edu", university: "Carnegie Mellon", researchFocus: "Medical devices; human health; bioengineering", dateSent: "2026-06-21", status: "sent" }
];

// ─── Colleges Data (merged from user research — 26 universities) ───
export const collegesData: CollegeEntry[] = [
  { sno: 1, name: "Stanford University", location: "Stanford, CA", focusAreas: "Fluids, Mfg, Materials, Thermo", admissionUrl: "https://me.stanford.edu/academics-admissions/graduate-programs/doctoral-program/phd-admissions", duration: "5 yrs", cost: "$71,235/yr" },
  { sno: 2, name: "Caltech", location: "Pasadena, CA", focusAreas: "Fluids, Materials, Thermo, Aero", admissionUrl: "https://mce.caltech.edu/academics/grad/graduate-degree-in-applied-mechanics", duration: "4 yrs", cost: "$71,082/yr" },
  { sno: 3, name: "Cornell University", location: "Ithaca, NY", focusAreas: "Fluids, Materials, Mfg, Thermo", admissionUrl: "https://www.duffield.cornell.edu/mae/phd/phd-admissions/", duration: "3 yrs", cost: "$23,318/yr" },
  { sno: 4, name: "U Michigan-Ann Arbor", location: "Ann Arbor, MI", focusAreas: "Fluids, Mfg, Materials, Aero", admissionUrl: "https://me.engin.umich.edu/admissions/graduate/", duration: "3 yrs", cost: "$119,459/yr" },
  { sno: 5, name: "Northwestern University", location: "Evanston, IL", focusAreas: "Materials, Fluids, Mechanics", admissionUrl: "https://www.tgs.northwestern.edu/admission/", duration: "4 yrs", cost: "$62,859/yr" },
  { sno: 6, name: "Carnegie Mellon University", location: "Pittsburgh, PA", focusAreas: "Mfg, Materials, Fluids", admissionUrl: "https://www.meche.engineering.cmu.edu/education/graduate-programs/phd/", duration: "3 yrs", cost: "$57,459/yr" },
  { sno: 7, name: "UW-Madison", location: "Madison, WI", focusAreas: "Mfg, Fluids, Thermo, Materials", admissionUrl: "https://engineering.wisc.edu/programs/degrees/mechanical-engineering-phd/", duration: "5 yrs", cost: "$28,847/yr" },
  { sno: 8, name: "Ohio State University", location: "Columbus, OH", focusAreas: "Mfg, Fluids, Thermo, Aero", admissionUrl: "https://gpadmissions.osu.edu/programs/program.aspx?prog=0136", duration: "5 yrs", cost: "$16,059/yr" },
  { sno: 9, name: "U New Mexico", location: "Albuquerque, NM", focusAreas: "Mfg, Materials", admissionUrl: "https://grad.unm.edu/", duration: "4 yrs", cost: "$38,941/yr" },
  { sno: 10, name: "Southern Methodist U", location: "Dallas, TX", focusAreas: "Mfg, Fluids", admissionUrl: "https://www.smu.edu/lyle/departments/me/doctoral-programs", duration: "3 yrs", cost: "$42,882/yr" },
  { sno: 11, name: "U Vermont", location: "Burlington, VT", focusAreas: "Materials, Fluids", admissionUrl: "https://www.uvm.edu/cems/me/program/phd-mechanical-engineering", duration: "4 yrs", cost: "$57,847/yr" },
  { sno: 12, name: "U Miami", location: "Coral Gables, FL", focusAreas: "Materials, Fluids", admissionUrl: "https://bulletin.miami.edu/graduate-academic-programs/engineering/", duration: "4 yrs", cost: "$71,141/yr" },
  { sno: 13, name: "UIC", location: "Chicago, IL", focusAreas: "Fluids, Mfg", admissionUrl: "https://mie.uic.edu/graduate/phd-programs/", duration: "4 yrs", cost: "$36,471/yr" },
  { sno: 14, name: "U Utah", location: "Salt Lake City, UT", focusAreas: "Fluids, Thermo", admissionUrl: "https://www.mech.utah.edu/grads/admissions/", duration: "5 yrs", cost: "$22,494/yr" },
  { sno: 15, name: "U Central Florida", location: "Orlando, FL", focusAreas: "Fluids, Mfg, Thermo", admissionUrl: "https://mae.ucf.edu/ph-d-in-mechanical-engineering/", duration: "4 yrs", cost: "$25,776/yr" },
  { sno: 16, name: "SUNY Buffalo", location: "Buffalo, NY", focusAreas: "Fluids, Materials", admissionUrl: "https://www.buffalo.edu/grad/programs/mechanical-engineering-phd.html", duration: "5 yrs", cost: "$28,024/yr" },
  { sno: 17, name: "U Iowa", location: "Iowa City, IA", focusAreas: "Fluids, Mfg", admissionUrl: "https://engineering.uiowa.edu/mechanical-engineering-graduate-program/", duration: "5 yrs", cost: "$37,329/yr" },
  { sno: 18, name: "Louisiana State U", location: "Baton Rouge, LA", focusAreas: "Fluids, Materials", admissionUrl: "https://www.lsu.edu/eng/mie/graduate/me/pme-program.php", duration: "4 yrs", cost: "$33,376/yr" },
  { sno: 19, name: "U Georgia", location: "Athens, GA", focusAreas: "Materials, Mechanics", admissionUrl: "https://engineering.uga.edu/degree/phd-mechanical-engineering/", duration: "4 yrs", cost: "$33,835/yr" },
  { sno: 20, name: "Kansas State U", location: "Manhattan, KS", focusAreas: "Mfg, Thermo", admissionUrl: "https://www.sdstate.edu/programs/graduate/mechanical-engineering-phd", duration: "3 yrs", cost: "$22,094/yr" },
  { sno: 21, name: "U Tennessee Knoxville", location: "Knoxville, TN", focusAreas: "Mfg, Materials", admissionUrl: "https://tickle.utk.edu/mae/academics/graduate/mechanical-engineering-phd/", duration: "3 yrs", cost: "$36,200/yr" },
  { sno: 22, name: "U Puerto Rico Mayaguez", location: "Mayaguez, PR", focusAreas: "Mfg, Materials", admissionUrl: "https://www.uprm.edu/inme/academic/grad/prospecgrad/applymegrad/", duration: "4 yrs", cost: "$7,235/yr" },
  { sno: 23, name: "U Oklahoma Norman", location: "Norman, OK", focusAreas: "Fluids, Thermo", admissionUrl: "https://www.ou.edu/coe/ame/academics/graduate/phd-requirements", duration: "3 yrs", cost: "$28,259/yr" },
  { sno: 24, name: "South Dakota State U", location: "Brookings, SD", focusAreas: "Mfg, Materials", admissionUrl: "https://www.sdstate.edu/programs/graduate/mechanical-engineering-phd", duration: "3 yrs", cost: "$22,000/yr" },
  { sno: 25, name: "USC-Aiken", location: "Aiken, SC", focusAreas: "Mfg, Fluids", admissionUrl: "https://sc.edu/study/majors_and_degrees/mechanical-engineering-phd.php", duration: "5 yrs", cost: "$16,682/yr" },
  { sno: 26, name: "U South Florida Tampa", location: "Tampa, FL", focusAreas: "Fluids, Mfg", admissionUrl: "https://www.usf.edu/engineering/mae/graduate/grad-admissions.aspx", duration: "4 yrs", cost: "$22,400/yr" },
  { sno: 27, name: "NYU Tandon", location: "Brooklyn, NY", focusAreas: "Fluids, Mfg, Materials", admissionUrl: "https://engineering.nyu.edu/academics/programs/mechanical-engineering-phd", duration: "5 yrs", cost: "$78,541/yr" },
];

// ─── Calendar Events ───
export const calendarData: CalendarEvent[] = [
  { id: "1", date: "2026-06-26", title: "Follow up: Prof. Zufferey (MIT)", description: "Returns from travel. Send follow-up email.", type: "follow_up", professor: "Raphael Zufferey" },
  { id: "2", date: "2026-07-15", title: "MIT Fall 2026 Application Deadline", description: "Check MIT MechE PhD deadlines. Slotine + Slocum recommended formal application.", type: "deadline", professor: null },
  { id: "3", date: "2026-06-23", title: "Follow up: Una Shehan (MIT Admissions)", description: "Contacted per Slotine's referral. Follow up if no response by Wednesday.", type: "action", professor: null },
  { id: "4", date: "2026-06-30", title: "Check Ian Hunter's Lab", description: "He called you 'ideal fit' — will notify when opening. Check back monthly.", type: "follow_up", professor: "Ian Hunter" },
  { id: "5", date: "2026-08-01", title: "Stanford PhD Application Opens", description: "Check Stanford ME PhD application portal for Fall 2027 admission cycle.", type: "deadline", professor: null },
  { id: "6", date: "2026-09-15", title: "Cornell MAE PhD Application Deadline", description: "Check Cornell Sibley School PhD application deadline for Fall 2027.", type: "deadline", professor: null },
];

// ─── Notifications ───
export const notificationsData: NotificationItem[] = [
  { id: "1", date: "2026-06-21", title: "Prof. Slotine Responded", message: "Apply through formal MIT admissions. Contact Una Shehan (oona@mit.edu). Email sent.", type: "info", read: true, actionable: true },
  { id: "2", date: "2026-06-21", title: "Prof. Slocum — Retiring", message: "No new students. Suggested finding industry-sponsored research topics.", type: "info", read: true, actionable: false },
  { id: "3", date: "2026-06-21", title: "Prof. Hunter — Positive!", message: "Called you 'ideal fit' but lab is full. Will notify when opening available.", type: "positive", read: true, actionable: false },
  { id: "4", date: "2026-06-26", title: "Follow up: Prof. Zufferey", message: "Returns from travel June 26. Prepare follow-up email.", type: "reminder", read: false, actionable: true },
  { id: "5", date: "2026-06-30", title: "Pipeline Progress", message: "Human-like outreach pipeline running. 14+ sent, 7 responses (50% response rate!).", type: "positive", read: false, actionable: false },
  { id: "6", date: "2026-07-01", title: "Admission Deadlines Approaching", message: "Multiple universities have Fall deadlines in August-September. Start preparing applications.", type: "warning", read: false, actionable: true },
];
